### ISSUE TITLE
Copyright notice

### ISSUE THREAD

**Issue by wizofe** [rishavs/love2d-bunnymark#4]
I am forking your project to use for a simple SBC benchmarking fo embedded systems. I added a few extra things like memory profiling in MB and current stack. I added your Copyright note and added on top a GPLv2 Copyright notice. 

Is that fine with you or do you had another Copyright in mind?

**Comment by rishavs** [comment]
Hi @wizofe 
I want the license to be as permissible as possible. I have always been partial to MIT licensing.
I fear i am not knowledgeable about the details of GPLv2.

**Comment by wizofe** [comment]
@rishavs That's great. I saw you added a fully permissive license but that looks more like public domain to me. I am fine to go with that; I'll keep the GPL as it ensures that everybody who makes modifications can share them as well; that's one of the main differences between MIT and GPL.

If you are fine with that I will keep your name and the license as I have :) Thanks!

**Comment by rishavs** [comment]
sounds good.
